DATASET_ROOT: "../mednode/"
CHECKPOINT_ROOT: "../checkpoints/"
MODEL_ARCHITECTURE: "RESNET101"
OPTIMIZER: "SGD"
LEARNING_RATE: 0.0001
SCHEDULER_STEP: 7
SCHEDULER_GAMMA: 0.1
MOMENTUM: 0.9
NUM_WORKER: 4
BATCH_SIZE: 4
EPOCHS: 2
CROSS_VALIDATION_FOLDS: 2
