# DATASET_ROOT: It should have two subdirectories called [melanoma] and [not_melanoma].
# CHECKPOINT ROOT: A sub-directory will be generated to save logs, plots and checkpoint.
# MODEL_ARCHITECTURE: Choices are ["RESNET50", "RESNET101", "RESNET152"]
# LOAD_CHECKPOINT: Path to a checkpoint for transfer-learning.
# FINE_TUNE_FC: If True, all the layers, except fully-connected ones, will be frozen.
# INPUT_SIZE: Size of an input image (INPUT_SIZE x INPUT_SIZE).
# OPTIMIZER: Choices are ["ADAM", "SGD"].
# LEARNING_RATE: Learning rate value.
# SCHEDULER_STEP: Schedular's step value.
# SCHEDULER_GAMMA: Schedular's gamma value.
# MOMENTUM: Momentum value.
# NUM_WORKER: Number of workers.
# BATCH_SIZE: Batch size value.
# EPOCHS: Number of epochs.
# CROSS_VALIDATION_FOLDS: Number of cross-validation folds.
# SINGLE_FOLD_SPLIT: A value to split the dataset (train/val) when CROSS_VALIDATION_FOLDS=1

DATASET_ROOT: "../mednode/"
CHECKPOINT_ROOT: "../checkpoints/"
MODEL_ARCHITECTURE: "RESNET101"
LOAD_CHECKPOINT: null
FINE_TUNE_FC: False
INPUT_SIZE: 400
OPTIMIZER: "ADAM"
LEARNING_RATE: 0.0001
SCHEDULER_STEP: 7
SCHEDULER_GAMMA: 0.1
MOMENTUM: 0.9
NUM_WORKER: 4
BATCH_SIZE: 4
EPOCHS: 3
CROSS_VALIDATION_FOLDS: 2
SINGLE_FOLD_SPLIT: 0.8