DATASET_ROOT: "../mednode/"
CHECKPOINT_ROOT: "../checkpoints/"
MODEL_ARCHITECTURE: "RESNET101"
LOAD_CHECKPOINT: null
FINE_TUNE_FC: False
INPUT_SIZE: 400
OPTIMIZER: "ADAM"
LEARNING_RATE: 0.0001
SCHEDULER_STEP: 7
SCHEDULER_GAMMA: 0.1
MOMENTUM: 0.9
NUM_WORKER: 4
BATCH_SIZE: 4
EPOCHS: 20
CROSS_VALIDATION_FOLDS: 1
SINGLE_FOLD_SPLIT: 0.8
